Vagrant.configure("2") do |config|
  config.vm.box = ENV.fetch("VAGRANT_BOX", "test/ubuntu-24.04")
  config.vm.boot_timeout = 600

  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.allowlist_verified = true
    v.vmx["ethernet0.virtualDev"] = "vmxnet3"
    v.vmx["usb_xhci.present"] = "TRUE"
    v.vmx["firmware"] = "efi"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true
end
